version: '3.8'

services:
  server:
    build:
      context: ./server
    image: hello-server
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    image: hello-client
    ports:
      - "8000:8000" 